# Site
title: awsub
description: Command line tool to run a batch jobs with ETL framework on AWS or other cloud computing resources.

# Meta
author:
    name: 'Hiromu OCHIAI (otiai10)'
    url: https://otiai10.github.io
github:
    is_project_page: true
    repository_url: https://github.com/otiai10/awsub
    repository_name: awsub
    owner_name: otiai10
    owner_url: https://github.com/otiai10

# Build
markdown: kramdown
theme: jekyll-theme-architect