# Site
title: hotsub
description: CLI tool to run a batch jobs with ETL/ExTL framework on AWS or other cloud services.

# Meta
author:
    name: 'Hiromu OCHIAI (otiai10)'
    url: https://otiai10.github.io
github:
    is_project_page: true
    repository_url: https://github.com/otiai10/hotsub
    repository_name: hotsub
    repository_nwo: github.com/otiai10/hotsub
    owner_name: otiai10
    owner_url: https://github.com/otiai10

# Build
markdown: kramdown
theme: jekyll-theme-minimal